#!/bin/bash -l

# Exit if we are not a CI role
if nubis-purpose ci; then
  echo "We are a CI node, starting Jenkins"
  /etc/init.d/jenkins start
else
  # Disable haul-admin role
  gzip /etc/consul/svc-haul-admin.json
  service consul reload
fi
