#!/bin/bash -l

# Exit if we are not a CI role
if nubis-purpose ci; then
  echo "We are a CI node, starting Jenkins"
  systemctl start jenkins
else
  # Disable haul-admin role
  gzip /etc/consul/svc-haul-admin.json
  systemctl reload consul

  # Stop docker, useless
  systemctl stop docker
fi
