#!/bin/bash

for domain in "$@"; do

#  safe_domain=$(echo "$domain" | sed -e's/\./_/g')

# For stage list
#domain="$domain.allizom.org"

sans=""
case $domain in
  www.*)
    sans=$(printf "sans = [\n  \"$domain\"\n]")
    domain=$(echo "$domain" | sed -e's/^www\.//g')
  ;;
esac
  

cat <<EOF
[[acme]]
main = "$domain"
$sans

EOF

done
