#!/bin/bash

for domain in "$*"; do

  safe_domain="$(echo $domain | sed -e's/\./_/g')"
  

cat <<EOF
module "$safe_domain" {
  source                 = "dns"
  region                 = "\${var.region}"
  environment            = "\${var.environment}"
  service_name           = "\${var.service_name}"
  route53_delegation_set = "\${aws_route53_delegation_set.haul-delegation.id}"
  hosted_zone_ttl        = "3600"
  elb_address            = "\${module.load_balancer_web.address}"

  # Make sure to construct a unique zone name depending on the environment
  zone_name = "\${var.environment == "prod" ? "$domain" : join(".", list(var.environment, "$domain.allizom.org"))}"
}

EOF

done
